#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 22-10-07 11:01 AM
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace Qasar.Mva
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// Comment describing your root element.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVARequest", TypeName="MVARequest")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVARequest
    {
        
        /// <remarks/>
        private MVARequestClass[] classes;
        
        /// <remarks/>
        private MVARequestClient[] clients;
        
        /// <remarks/>
        private int noResources;
        
        /// <remarks/>
        private int noClasses;
        
        /// <remarks/>
        private int noClients;
        
        public MVARequest()
        {
        }
        
        public MVARequest(MVARequestClass[] classes, MVARequestClient[] clients, int noResources, int noClasses, int noClients)
        {
            this.classes = classes;
            this.clients = clients;
            this.noResources = noResources;
            this.noClasses = noClasses;
            this.noClients = noClients;
        }
        
        /// <summary>
        /// Use this node for dynamic load balancing, self-healing tests and perf optimisation tests.
        /// </summary>
        [System.Xml.Serialization.XmlArrayItemAttribute("Class", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Classes")]
        public MVARequestClass[] Classes
        {
            get
            {
                return this.classes;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Classes");
                }
                if ((this.classes != value))
                {
                    this.classes = value;
                }
            }
        }
        
        /// <summary>
        /// Use this node to specify client-based admission control.
        /// </summary>
        [System.Xml.Serialization.XmlArrayItemAttribute("Client", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Clients")]
        public MVARequestClient[] Clients
        {
            get
            {
                return this.clients;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Clients");
                }
                if ((this.clients != value))
                {
                    this.clients = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NoResources")]
        public int NoResources
        {
            get
            {
                return this.noResources;
            }
            set
            {
                if ((this.noResources != value))
                {
                    this.noResources = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NoClasses")]
        public int NoClasses
        {
            get
            {
                return this.noClasses;
            }
            set
            {
                if ((this.noClasses != value))
                {
                    this.noClasses = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="NoClients")]
        public int NoClients
        {
            get
            {
                return this.noClients;
            }
            set
            {
                if ((this.noClients != value))
                {
                    this.noClients = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVARequest", TypeName="MVARequestClass")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVARequestClass
    {
        
        /// <remarks/>
        private int classID;
        
        /// <remarks/>
        private bool include;
        
        /// <remarks/>
        private int totalPopulation;
        
        /// <remarks/>
        private MVARequestClassResource[] resources;
        
        public MVARequestClass()
        {
            this.Include = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ClassID")]
        public int ClassID
        {
            get
            {
                return this.classID;
            }
            set
            {
                if ((this.classID != value))
                {
                    this.classID = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Include")]
        public bool Include
        {
            get
            {
                return this.include;
            }
            set
            {
                if ((this.include != value))
                {
                    this.include = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TotalPopulation")]
        public int TotalPopulation
        {
            get
            {
                return this.totalPopulation;
            }
            set
            {
                if ((this.totalPopulation != value))
                {
                    this.totalPopulation = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Resources")]
        public MVARequestClassResource[] Resources
        {
            get
            {
                return this.resources;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Resources");
                }
                if ((this.resources != value))
                {
                    this.resources = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVARequest", TypeName="MVARequestClassResource")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVARequestClassResource
    {
        
        /// <remarks/>
        private int resourceID;
        
        /// <remarks/>
        private bool @internal;
        
        /// <remarks/>
        private double serviceTime;
        
        /// <remarks/>
        private double loadRatio;
        
        /// <remarks/>
        private double equivLoad;
        
        public MVARequestClassResource()
        {
            this.Internal = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ResourceID")]
        public int ResourceID
        {
            get
            {
                return this.resourceID;
            }
            set
            {
                if ((this.resourceID != value))
                {
                    this.resourceID = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Internal")]
        public bool Internal
        {
            get
            {
                return this.@internal;
            }
            set
            {
                if ((this.@internal != value))
                {
                    this.@internal = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ServiceTime")]
        public double ServiceTime
        {
            get
            {
                return this.serviceTime;
            }
            set
            {
                if ((this.serviceTime != value))
                {
                    this.serviceTime = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="LoadRatio")]
        public double LoadRatio
        {
            get
            {
                return this.loadRatio;
            }
            set
            {
                if ((this.loadRatio != value))
                {
                    this.loadRatio = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EquivLoad")]
        public double EquivLoad
        {
            get
            {
                return this.equivLoad;
            }
            set
            {
                if ((this.equivLoad != value))
                {
                    this.equivLoad = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qasar.shellysaunders.co.uk/MVAResponse", TypeName="MetricsType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MetricsType
    {
        
        /// <remarks/>
        private double serviceDemand;
        
        /// <remarks/>
        private decimal utilization;
        
        /// <remarks/>
        private double responseTime;
        
        /// <remarks/>
        private double throughput;
        
        public MetricsType()
        {
        }
        
        public MetricsType(double serviceDemand, decimal utilization, double responseTime, double throughput)
        {
            this.serviceDemand = serviceDemand;
            this.utilization = utilization;
            this.responseTime = responseTime;
            this.throughput = throughput;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ServiceDemand")]
        public double ServiceDemand
        {
            get
            {
                return this.serviceDemand;
            }
            set
            {
                if ((this.serviceDemand != value))
                {
                    this.serviceDemand = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Utilization")]
        public decimal Utilization
        {
            get
            {
                return this.utilization;
            }
            set
            {
                if ((this.utilization != value))
                {
                    this.utilization = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ResponseTime")]
        public double ResponseTime
        {
            get
            {
                return this.responseTime;
            }
            set
            {
                if ((this.responseTime != value))
                {
                    this.responseTime = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Throughput")]
        public double Throughput
        {
            get
            {
                return this.throughput;
            }
            set
            {
                if ((this.throughput != value))
                {
                    this.throughput = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVARequest", TypeName="MVARequestClient")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVARequestClient
    {
        
        /// <remarks/>
        private int clientID;
        
        /// <remarks/>
        private bool include;
        
        public MVARequestClient()
        {
            this.Include = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ClientID")]
        public int ClientID
        {
            get
            {
                return this.clientID;
            }
            set
            {
                if ((this.clientID != value))
                {
                    this.clientID = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Include")]
        public bool Include
        {
            get
            {
                return this.include;
            }
            set
            {
                if ((this.include != value))
                {
                    this.include = value;
                }
            }
        }
    }
    
    /// <summary>
    /// Comment describing your root element.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVAResponse", TypeName="MVAResponse")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVAResponse
    {
        
        /// <remarks/>
        private MVAResponseClass[] classes;
        
        /// <remarks/>
        private MVAResponseClient[] clients;
        
        public MVAResponse()
        {
        }
        
        public MVAResponse(MVAResponseClass[] classes, MVAResponseClient[] clients)
        {
            this.classes = classes;
            this.clients = clients;
        }
        
        /// <summary>
        /// Use this node for dynamic load balancing, self-healing tests and perf optimisation tests.
        /// </summary>
        [System.Xml.Serialization.XmlArrayItemAttribute("Class", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Classes")]
        public MVAResponseClass[] Classes
        {
            get
            {
                return this.classes;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Classes");
                }
                if ((this.classes != value))
                {
                    this.classes = value;
                }
            }
        }
        
        /// <summary>
        /// Use this node to specify client-based admission control.
        /// </summary>
        [System.Xml.Serialization.XmlArrayItemAttribute("Client", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Clients")]
        public MVAResponseClient[] Clients
        {
            get
            {
                return this.clients;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Clients");
                }
                if ((this.clients != value))
                {
                    this.clients = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVAResponse", TypeName="MVAResponseClass")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVAResponseClass
    {
        
        /// <remarks/>
        private int classID;
        
        /// <remarks/>
        private MetricsType metrics;
        
        /// <remarks/>
        private bool include;
        
        /// <remarks/>
        private MVAResponseClassResource[] resources;
        
        public MVAResponseClass()
        {
            this.Include = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ClassID")]
        public int ClassID
        {
            get
            {
                return this.classID;
            }
            set
            {
                if ((this.classID != value))
                {
                    this.classID = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Metrics")]
        public MetricsType Metrics
        {
            get
            {
                return this.metrics;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Metrics");
                }
                if ((this.metrics != value))
                {
                    this.metrics = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Include")]
        public bool Include
        {
            get
            {
                return this.include;
            }
            set
            {
                if ((this.include != value))
                {
                    this.include = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Resources")]
        public MVAResponseClassResource[] Resources
        {
            get
            {
                return this.resources;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Resources");
                }
                if ((this.resources != value))
                {
                    this.resources = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVAResponse", TypeName="MVAResponseClassResource")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVAResponseClassResource
    {
        
        /// <remarks/>
        private int resourceID;
        
        /// <remarks/>
        private bool @internal;
        
        /// <remarks/>
        private double equivLoad;
        
        /// <remarks/>
        private bool equivLoadSpecified;
        
        /// <remarks/>
        private MetricsType metrics;
        
        public MVAResponseClassResource()
        {
            this.Internal = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ResourceID")]
        public int ResourceID
        {
            get
            {
                return this.resourceID;
            }
            set
            {
                if ((this.resourceID != value))
                {
                    this.resourceID = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Internal")]
        public bool Internal
        {
            get
            {
                return this.@internal;
            }
            set
            {
                if ((this.@internal != value))
                {
                    this.@internal = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="EquivLoad")]
        public double EquivLoad
        {
            get
            {
                return this.equivLoad;
            }
            set
            {
                if ((this.equivLoad != value))
                {
                    this.equivLoad = value;
                    this.equivLoadSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EquivLoadSpecified
        {
            get
            {
                return this.equivLoadSpecified;
            }
            set
            {
                if ((this.equivLoadSpecified != value))
                {
                    this.equivLoadSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Metrics")]
        public MetricsType Metrics
        {
            get
            {
                return this.metrics;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Metrics");
                }
                if ((this.metrics != value))
                {
                    this.metrics = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://qasar.shellysaunders.co.uk/MVAResponse", TypeName="MVAResponseClient")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MVAResponseClient
    {
        
        /// <remarks/>
        private int clientID;
        
        /// <remarks/>
        private bool include;
        
        public MVAResponseClient()
        {
            this.Include = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ClientID")]
        public int ClientID
        {
            get
            {
                return this.clientID;
            }
            set
            {
                if ((this.clientID != value))
                {
                    this.clientID = value;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Include")]
        public bool Include
        {
            get
            {
                return this.include;
            }
            set
            {
                if ((this.include != value))
                {
                    this.include = value;
                }
            }
        }
    }
}
