#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 02-12-07 02:13 PM
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace Qasar.Sla
{
    using System.Diagnostics;
    using System.ComponentModel;
    using System;
    using System.Xml.Serialization;
    
    
    public interface IQasarSla
    {

        void SetWsqos(Wsqos wsqos1, string slaFile);

        Wsqos GetWsqos(string slaFile);
    }
}
