#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 02-12-07 02:13 PM
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace Qasar.Sla
{
    using System.Diagnostics;
    using System.ComponentModel;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="wsqos")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class Wsqos
    {
        
        /// <remarks/>
        private WsqosDefinition definition;
        
        public Wsqos()
        {
        }
        
        public Wsqos(WsqosDefinition definition)
        {
            this.definition = definition;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="definition")]
        public WsqosDefinition Definition
        {
            get
            {
                return this.definition;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("Definition");
                }
                if ((this.definition != value))
                {
                    this.definition = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="wsqosDefinition")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class WsqosDefinition
    {
        
        /// <remarks/>
        private object item;
        
        public WsqosDefinition()
        {
        }
        
        public WsqosDefinition(object item)
        {
            this.item = item;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("offers", typeof(WsqosDefinitionOffers), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ontology", typeof(TOntology), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("requirements", typeof(TQoSDefinition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object Item
        {
            get
            {
                return this.item;
            }
            set
            {
                if ((this.item != value))
                {
                    this.item = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="wsqosDefinitionOffers")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class WsqosDefinitionOffers
    {
        
        /// <remarks/>
        private WsqosDefinitionOffersInclude[] include;
        
        /// <remarks/>
        private WsqosDefinitionOffersQosOffer[] qosOffer;
        
        public WsqosDefinitionOffers()
        {
        }
        
        public WsqosDefinitionOffers(WsqosDefinitionOffersInclude[] include, WsqosDefinitionOffersQosOffer[] qosOffer)
        {
            this.include = include;
            this.qosOffer = qosOffer;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("include", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsqosDefinitionOffersInclude[] Include
        {
            get
            {
                return this.include;
            }
            set
            {

                if ((this.include != value))
                {
                    this.include = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("qosOffer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsqosDefinitionOffersQosOffer[] QosOffer
        {
            get
            {
                return this.qosOffer;
            }
            set
            {

                if ((this.qosOffer != value))
                {
                    this.qosOffer = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="wsqosDefinitionOffersInclude")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class WsqosDefinitionOffersInclude
    {
        
        /// <remarks/>
        private string url;
        
        public WsqosDefinitionOffersInclude()
        {
        }
        
        public WsqosDefinitionOffersInclude(string url)
        {
            this.url = url;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="url")]
        public string Url
        {
            get
            {
                return this.url;
            }
            set
            {
                if ((this.url != value))
                {
                    this.url = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tPrice")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TPrice
    {
        
        /// <remarks/>
        private string currency;
        
        /// <remarks/>
        private float value;
        
        public TPrice()
        {
            this.currency = "EUR";
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="currency")]
        [System.ComponentModel.DefaultValueAttribute("EUR")]
        public string Currency
        {
            get
            {
                return this.currency;
            }
            set
            {
                if ((this.currency != value))
                {
                    this.currency = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tProtocol")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TProtocol
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string ontology;
        
        /// <remarks/>
        private string value;
        
        public TProtocol()
        {
        }
        
        public TProtocol(string name, string ontology, string value)
        {
            this.name = name;
            this.ontology = ontology;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="ontology")]
        public string Ontology
        {
            get
            {
                return this.ontology;
            }
            set
            {
                if ((this.ontology != value))
                {
                    this.ontology = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tPriority")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TPriority
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string ontology;
        
        /// <remarks/>
        private int value;
        
        public TPriority()
        {
        }
        
        public TPriority(string name, string ontology, int value)
        {
            this.name = name;
            this.ontology = ontology;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="ontology")]
        public string Ontology
        {
            get
            {
                return this.ontology;
            }
            set
            {
                if ((this.ontology != value))
                {
                    this.ontology = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tMetric")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TMetric
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string ontology;
        
        /// <remarks/>
        private double value;
        
        public TMetric()
        {
        }
        
        public TMetric(string name, string ontology, double value)
        {
            this.name = name;
            this.ontology = ontology;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="ontology")]
        public string Ontology
        {
            get
            {
                return this.ontology;
            }
            set
            {
                if ((this.ontology != value))
                {
                    this.ontology = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSInfo
    {
        
        /// <remarks/>
        private TQoSInfoServerQoSMetrics serverQoSMetrics;
        
        /// <remarks/>
        private TQoSInfoTransportQoSPriorities transportQoSPriorities;
        
        /// <remarks/>
        private TQoSInfoSecurityAndTransaction[] securityAndTransaction;
        
        /// <remarks/>
        private object[] extension;
        
        public TQoSInfo()
        {
        }
        
        public TQoSInfo(TQoSInfoServerQoSMetrics serverQoSMetrics, TQoSInfoTransportQoSPriorities transportQoSPriorities, TQoSInfoSecurityAndTransaction[] securityAndTransaction, object[] extension)
        {
            this.serverQoSMetrics = serverQoSMetrics;
            this.transportQoSPriorities = transportQoSPriorities;
            this.securityAndTransaction = securityAndTransaction;
            this.extension = extension;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="serverQoSMetrics")]
        public TQoSInfoServerQoSMetrics ServerQoSMetrics
        {
            get
            {
                return this.serverQoSMetrics;
            }
            set
            {

                if ((this.serverQoSMetrics != value))
                {
                    this.serverQoSMetrics = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="transportQoSPriorities")]
        public TQoSInfoTransportQoSPriorities TransportQoSPriorities
        {
            get
            {
                return this.transportQoSPriorities;
            }
            set
            {
                if ((this.transportQoSPriorities != value))
                {
                    this.transportQoSPriorities = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("securityAndTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TQoSInfoSecurityAndTransaction[] SecurityAndTransaction
        {
            get
            {
                return this.securityAndTransaction;
            }
            set
            {

                if ((this.securityAndTransaction != value))
                {
                    this.securityAndTransaction = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Extension
        {
            get
            {
                return this.extension;
            }
            set
            {
                if ((this.extension != value))
                {
                    this.extension = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSInfoServerQoSMetrics")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSInfoServerQoSMetrics
    {
        
        /// <remarks/>
        private float processingTime;
        
        /// <remarks/>
        private bool processingTimeSpecified;
        
        /// <remarks/>
        private float requestsPerSecond;
        
        /// <remarks/>
        private bool requestsPerSecondSpecified;
        
        /// <remarks/>
        private float reliability;
        
        /// <remarks/>
        private bool reliabilitySpecified;
        
        /// <remarks/>
        private float availability;
        
        /// <remarks/>
        private bool availabilitySpecified;
        
        /// <remarks/>
        private TMetric[] customMetric;
        
        public TQoSInfoServerQoSMetrics()
        {
        }
        
        public TQoSInfoServerQoSMetrics(float processingTime, bool processingTimeSpecified, float requestsPerSecond, bool requestsPerSecondSpecified, float reliability, bool reliabilitySpecified, float availability, bool availabilitySpecified, TMetric[] customMetric)
        {
            this.processingTime = processingTime;
            this.processingTimeSpecified = processingTimeSpecified;
            this.requestsPerSecond = requestsPerSecond;
            this.requestsPerSecondSpecified = requestsPerSecondSpecified;
            this.reliability = reliability;
            this.reliabilitySpecified = reliabilitySpecified;
            this.availability = availability;
            this.availabilitySpecified = availabilitySpecified;
            this.customMetric = customMetric;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="processingTime")]
        public float ProcessingTime
        {
            get
            {
                return this.processingTime;
            }
            set
            {
                if ((this.processingTime != value))
                {
                    this.processingTime = value;
                    this.processingTimeSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessingTimeSpecified
        {
            get
            {
                return this.processingTimeSpecified;
            }
            set
            {
                if ((this.processingTimeSpecified != value))
                {
                    this.processingTimeSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="requestsPerSecond")]
        public float RequestsPerSecond
        {
            get
            {
                return this.requestsPerSecond;
            }
            set
            {
                if ((this.requestsPerSecond != value))
                {
                    this.requestsPerSecond = value;
                    this.requestsPerSecondSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestsPerSecondSpecified
        {
            get
            {
                return this.requestsPerSecondSpecified;
            }
            set
            {
                if ((this.requestsPerSecondSpecified != value))
                {
                    this.requestsPerSecondSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="reliability")]
        public float Reliability
        {
            get
            {
                return this.reliability;
            }
            set
            {
                if ((this.reliability != value))
                {
                    this.reliability = value;
                    this.reliabilitySpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReliabilitySpecified
        {
            get
            {
                return this.reliabilitySpecified;
            }
            set
            {
                if ((this.reliabilitySpecified != value))
                {
                    this.reliabilitySpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="availability")]
        public float Availability
        {
            get
            {
                return this.availability;
            }
            set
            {
                if ((this.availability != value))
                {
                    this.availability = value;
                    this.availabilitySpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilitySpecified
        {
            get
            {
                return this.availabilitySpecified;
            }
            set
            {
                if ((this.availabilitySpecified != value))
                {
                    this.availabilitySpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("customMetric", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TMetric[] CustomMetric
        {
            get
            {
                return this.customMetric;
            }
            set
            {

                if ((this.customMetric != value))
                {
                    this.customMetric = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSInfoTransportQoSPriorities")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSInfoTransportQoSPriorities
    {
        
        /// <remarks/>
        private int delay;
        
        /// <remarks/>
        private bool delaySpecified;
        
        /// <remarks/>
        private int jitter;
        
        /// <remarks/>
        private bool jitterSpecified;
        
        /// <remarks/>
        private int throughput;
        
        /// <remarks/>
        private bool throughputSpecified;
        
        /// <remarks/>
        private int packetLoss;
        
        /// <remarks/>
        private bool packetLossSpecified;
        
        /// <remarks/>
        private TPriority[] customPriority;
        
        public TQoSInfoTransportQoSPriorities()
        {
        }
        
        public TQoSInfoTransportQoSPriorities(int delay, bool delaySpecified, int jitter, bool jitterSpecified, int throughput, bool throughputSpecified, int packetLoss, bool packetLossSpecified, TPriority[] customPriority)
        {
            this.delay = delay;
            this.delaySpecified = delaySpecified;
            this.jitter = jitter;
            this.jitterSpecified = jitterSpecified;
            this.throughput = throughput;
            this.throughputSpecified = throughputSpecified;
            this.packetLoss = packetLoss;
            this.packetLossSpecified = packetLossSpecified;
            this.customPriority = customPriority;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="delay")]
        public int Delay
        {
            get
            {
                return this.delay;
            }
            set
            {
                if ((this.delay != value))
                {
                    this.delay = value;
                    this.delaySpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelaySpecified
        {
            get
            {
                return this.delaySpecified;
            }
            set
            {
                if ((this.delaySpecified != value))
                {
                    this.delaySpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="jitter")]
        public int Jitter
        {
            get
            {
                return this.jitter;
            }
            set
            {
                if ((this.jitter != value))
                {
                    this.jitter = value;
                    this.jitterSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JitterSpecified
        {
            get
            {
                return this.jitterSpecified;
            }
            set
            {
                if ((this.jitterSpecified != value))
                {
                    this.jitterSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="throughput")]
        public int Throughput
        {
            get
            {
                return this.throughput;
            }
            set
            {
                if ((this.throughput != value))
                {
                    this.throughput = value;
                    this.throughputSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThroughputSpecified
        {
            get
            {
                return this.throughputSpecified;
            }
            set
            {
                if ((this.throughputSpecified != value))
                {
                    this.throughputSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="packetLoss")]
        public int PacketLoss
        {
            get
            {
                return this.packetLoss;
            }
            set
            {
                if ((this.packetLoss != value))
                {
                    this.packetLoss = value;
                    this.packetLossSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PacketLossSpecified
        {
            get
            {
                return this.packetLossSpecified;
            }
            set
            {
                if ((this.packetLossSpecified != value))
                {
                    this.packetLossSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("customPriority", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TPriority[] CustomPriority
        {
            get
            {
                return this.customPriority;
            }
            set
            {

                if ((this.customPriority != value))
                {
                    this.customPriority = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSInfoSecurityAndTransaction")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSInfoSecurityAndTransaction
    {
        
        /// <remarks/>
        private TProtocol[] protocol;
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private TRequires requires;
        
        public TQoSInfoSecurityAndTransaction()
        {
        }
        
        public TQoSInfoSecurityAndTransaction(TProtocol[] protocol, string name, TRequires requires)
        {
            this.protocol = protocol;
            this.name = name;
            this.requires = requires;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("protocol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TProtocol[] Protocol
        {
            get
            {
                return this.protocol;
            }
            set
            {

                if ((this.protocol != value))
                {
                    this.protocol = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="requires")]
        public TRequires Requires
        {
            get
            {
                return this.requires;
            }
            set
            {
                if ((this.requires != value))
                {
                    this.requires = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tRequires")]
    public enum TRequires
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="none")]
        None,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="one")]
        One,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="all")]
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSDefinition")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSDefinition
    {
        
        /// <remarks/>
        private TQoSInfo defaultQoSInfo;
        
        /// <remarks/>
        private TQoSDefinitionOperationQoSInfo[] operationQoSInfo;
        
        /// <remarks/>
        private TQoSDefinitionContractAndMonitoring[] contractAndMonitoring;
        
        /// <remarks/>
        private TPrice price;
        
        /// <remarks/>
        private object[] extension;
        
        /// <remarks/>
        private string name;
        
        public TQoSDefinition()
        {
        }
        
        public TQoSDefinition(TQoSInfo defaultQoSInfo, TQoSDefinitionOperationQoSInfo[] operationQoSInfo, TQoSDefinitionContractAndMonitoring[] contractAndMonitoring, TPrice price, object[] extension, string name)
        {
            this.defaultQoSInfo = defaultQoSInfo;
            this.operationQoSInfo = operationQoSInfo;
            this.contractAndMonitoring = contractAndMonitoring;
            this.price = price;
            this.extension = extension;
            this.name = name;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="defaultQoSInfo")]
        public TQoSInfo DefaultQoSInfo
        {
            get
            {
                return this.defaultQoSInfo;
            }
            set
            {

                if ((this.defaultQoSInfo != value))
                {
                    this.defaultQoSInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("operationQoSInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TQoSDefinitionOperationQoSInfo[] OperationQoSInfo
        {
            get
            {
                return this.operationQoSInfo;
            }
            set
            {

                if ((this.operationQoSInfo != value))
                {
                    this.operationQoSInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("contractAndMonitoring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TQoSDefinitionContractAndMonitoring[] ContractAndMonitoring
        {
            get
            {
                return this.contractAndMonitoring;
            }
            set
            {

                if ((this.contractAndMonitoring != value))
                {
                    this.contractAndMonitoring = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="price")]
        public TPrice Price
        {
            get
            {
                return this.price;
            }
            set
            {

                if ((this.price != value))
                {
                    this.price = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Extension
        {
            get
            {
                return this.extension;
            }
            set
            {
                if ((this.extension != value))
                {
                    this.extension = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSDefinitionOperationQoSInfo")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSDefinitionOperationQoSInfo : TQoSInfo
    {
        
        /// <remarks/>
        private string name;
        
        public TQoSDefinitionOperationQoSInfo()
        {
        }
        
        public TQoSDefinitionOperationQoSInfo(string name)
        {
            this.name = name;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSDefinitionContractAndMonitoring")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSDefinitionContractAndMonitoring
    {
        
        /// <remarks/>
        private TProtocol[] protocol;
        
        /// <remarks/>
        private TQoSDefinitionContractAndMonitoringTrustedParty[] trustedParty;
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private TRequires requires;
        
        public TQoSDefinitionContractAndMonitoring()
        {
        }
        
        public TQoSDefinitionContractAndMonitoring(TProtocol[] protocol, TQoSDefinitionContractAndMonitoringTrustedParty[] trustedParty, string name, TRequires requires)
        {
            this.protocol = protocol;
            this.trustedParty = trustedParty;
            this.name = name;
            this.requires = requires;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("protocol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TProtocol[] Protocol
        {
            get
            {
                return this.protocol;
            }
            set
            {

                if ((this.protocol != value))
                {
                    this.protocol = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("trustedParty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TQoSDefinitionContractAndMonitoringTrustedParty[] TrustedParty
        {
            get
            {
                return this.trustedParty;
            }
            set
            {

                if ((this.trustedParty != value))
                {
                    this.trustedParty = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="requires")]
        public TRequires Requires
        {
            get
            {
                return this.requires;
            }
            set
            {
                if ((this.requires != value))
                {
                    this.requires = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.wsqos.net/schemas/", TypeName="tQoSDefinitionContractAndMonitoringTrustedParty")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TQoSDefinitionContractAndMonitoringTrustedParty
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string url;
        
        public TQoSDefinitionContractAndMonitoringTrustedParty()
        {
        }
        
        public TQoSDefinitionContractAndMonitoringTrustedParty(string name, string url)
        {
            this.name = name;
            this.url = url;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="url")]
        public string Url
        {
            get
            {
                return this.url;
            }
            set
            {
                if ((this.url != value))
                {
                    this.url = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tProtocolDefinition")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TProtocolDefinition
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string specificationUrl;
        
        /// <remarks/>
        private string description;
        
        public TProtocolDefinition()
        {
        }
        
        public TProtocolDefinition(string name, string specificationUrl, string description)
        {
            this.name = name;
            this.specificationUrl = specificationUrl;
            this.description = description;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="specificationUrl")]
        public string SpecificationUrl
        {
            get
            {
                return this.specificationUrl;
            }
            set
            {
                if ((this.specificationUrl != value))
                {
                    this.specificationUrl = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="description")]
        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                if ((this.description != value))
                {
                    this.description = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tPriorityDefinition")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TPriorityDefinition
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string description;
        
        public TPriorityDefinition()
        {
        }
        
        public TPriorityDefinition(string name, string description)
        {
            this.name = name;
            this.description = description;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="description")]
        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                if ((this.description != value))
                {
                    this.description = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tMetricDefinition")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TMetricDefinition
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private TDirection direction;
        
        /// <remarks/>
        private TUnit unit;
        
        /// <remarks/>
        private float percentile;
        
        /// <remarks/>
        private bool percentileSpecified;
        
        /// <remarks/>
        private TDataOwner dataOwner;
        
        /// <remarks/>
        private TDataScope dataScope;
        
        /// <remarks/>
        private float measurementIntervalLengthInSec;
        
        /// <remarks/>
        private string description;
        
        /// <remarks/>
        private string value;
        
        public TMetricDefinition()
        {
        }
        
        public TMetricDefinition(string name, TDirection direction, TUnit unit, float percentile, bool percentileSpecified, TDataOwner dataOwner, TDataScope dataScope, float measurementIntervalLengthInSec, string description, string value)
        {
            this.name = name;
            this.direction = direction;
            this.unit = unit;
            this.percentile = percentile;
            this.percentileSpecified = percentileSpecified;
            this.dataOwner = dataOwner;
            this.dataScope = dataScope;
            this.measurementIntervalLengthInSec = measurementIntervalLengthInSec;
            this.description = description;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="direction")]
        public TDirection Direction
        {
            get
            {
                return this.direction;
            }
            set
            {
                if ((this.direction != value))
                {
                    this.direction = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="unit")]
        public TUnit Unit
        {
            get
            {
                return this.unit;
            }
            set
            {
                if ((this.unit != value))
                {
                    this.unit = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="percentile")]
        public float Percentile
        {
            get
            {
                return this.percentile;
            }
            set
            {
                if ((this.percentile != value))
                {
                    this.percentile = value;
                    this.percentileSpecified = true;
                }
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentileSpecified
        {
            get
            {
                return this.percentileSpecified;
            }
            set
            {
                if ((this.percentileSpecified != value))
                {
                    this.percentileSpecified = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="dataOwner")]
        public TDataOwner DataOwner
        {
            get
            {
                return this.dataOwner;
            }
            set
            {
                if ((this.dataOwner != value))
                {
                    this.dataOwner = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="dataScope")]
        public TDataScope DataScope
        {
            get
            {
                return this.dataScope;
            }
            set
            {
                if ((this.dataScope != value))
                {
                    this.dataScope = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="measurementIntervalLengthInSec")]
        public float MeasurementIntervalLengthInSec
        {
            get
            {
                return this.measurementIntervalLengthInSec;
            }
            set
            {
                if ((this.measurementIntervalLengthInSec != value))
                {
                    this.measurementIntervalLengthInSec = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="description")]
        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                if ((this.description != value))
                {
                    this.description = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tDirection")]
    public enum TDirection
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="inc")]
        Inc,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="dec")]
        Dec,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tUnit")]
    public enum TUnit
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MS")]
        MS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="S")]
        S,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="M")]
        M,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="H")]
        H,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="D")]
        D,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="REQPERSEC")]
        REQPERSEC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BYTEPERSEC")]
        BYTEPERSEC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BITPERSEC")]
        BITPERSEC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PERCENT")]
        PERCENT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NONE")]
        NONE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tDataOwner")]
    public enum TDataOwner
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="all")]
        All,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="user")]
        User,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tDataScope")]
    public enum TDataScope
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="provider")]
        Provider,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="service")]
        Service,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="port")]
        Port,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wsqos.net/schemas/", TypeName="tOntology")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class TOntology
    {
        
        /// <remarks/>
        private object[] items;
        
        public TOntology()
        {
        }
        
        public TOntology(object[] items)
        {
            this.items = items;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("metricDefinition", typeof(TMetricDefinition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("priorityDefinition", typeof(TPriorityDefinition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("protocolDefinition", typeof(TProtocolDefinition), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="wsqosDefinitionOffersQosOffer")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class WsqosDefinitionOffersQosOffer : TQoSDefinition
    {
        
        /// <remarks/>
        private System.DateTime expires;
        
        public WsqosDefinitionOffersQosOffer()
        {
        }
        
        public WsqosDefinitionOffersQosOffer(System.DateTime expires)
        {
            this.expires = expires;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="expires")]
        public System.DateTime Expires
        {
            get
            {
                return this.expires;
            }
            set
            {
                if ((this.expires != value))
                {
                    this.expires = value;
                }
            }
        }
    }
}
